# Generated by Django 4.2.7 on 2023-11-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_outbox_middleware", "0003_auto_20170201_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboxrequestlog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
